// Generated by ReScript, PLEASE EDIT WITH CARE


function fromString(city) {
  if (city.length > 0) {
    return {
            TAG: "Ok",
            _0: city
          };
  } else {
    return {
            TAG: "Error",
            _0: "Invalid served city"
          };
  }
}

function toString(city) {
  return city;
}

function equals(city, other) {
  return city === other;
}

export {
  fromString ,
  toString ,
  equals ,
}
/* No side effect */
