// Generated by ReScript, PLEASE EDIT WITH CARE


function fromNumber(distance) {
  if (distance >= 0) {
    return {
            TAG: "Ok",
            _0: distance
          };
  } else {
    return {
            TAG: "Error",
            _0: "Invalid distance"
          };
  }
}

function toNumber(distance) {
  return distance;
}

export {
  fromNumber ,
  toNumber ,
}
/* No side effect */
