// Generated by ReScript, PLEASE EDIT WITH CARE


function make(route, distance) {
  return {
          route: route,
          distance: distance
        };
}

function route(itinerary) {
  return itinerary.route;
}

function distance(itinerary) {
  return itinerary.distance;
}

var Route;

var Distance;

export {
  Route ,
  Distance ,
  make ,
  route ,
  distance ,
}
/* No side effect */
