// Generated by ReScript, PLEASE EDIT WITH CARE


function fromNumber(fare) {
  if (fare >= 0) {
    return {
            TAG: "Ok",
            _0: fare
          };
  } else {
    return {
            TAG: "Error",
            _0: "Invalid fare"
          };
  }
}

function toNumber(fare) {
  return fare;
}

function multiply(fare, times) {
  return fromNumber(Math.imul(fare, times));
}

function add(fare, other) {
  return fromNumber(fare + other | 0);
}

export {
  fromNumber ,
  multiply ,
  add ,
  toNumber ,
}
/* No side effect */
