// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core_Fare from "./Core_Fare.res.js";
import * as Core_Distance from "./Core_Distance.res.js";
import * as Core_Itinerary from "./Core_Itinerary.res.js";

function forItinirary(itinerary, baseFare, farePerKilometer) {
  var distance = Core_Distance.toNumber(Core_Itinerary.distance(itinerary));
  var distanceFare = Core_Fare.multiply(farePerKilometer, distance);
  var fareResult;
  fareResult = distanceFare.TAG === "Ok" ? Core_Fare.add(distanceFare._0, baseFare) : ({
        TAG: "Error",
        _0: distanceFare._0
      });
  if (fareResult.TAG === "Ok") {
    return {
            TAG: "Ok",
            _0: {
              itinerary: itinerary,
              fare: fareResult._0
            }
          };
  } else {
    return {
            TAG: "Error",
            _0: fareResult._0
          };
  }
}

var ServedCity;

var Itinerary;

var Fare;

export {
  ServedCity ,
  Itinerary ,
  Fare ,
  forItinirary ,
}
/* No side effect */
