// Generated by ReScript, PLEASE EDIT WITH CARE


function fromNumber(fare) {
  if (fare >= 0) {
    return {
            TAG: "Ok",
            _0: fare
          };
  } else {
    return {
            TAG: "Error",
            _0: "Invalid fare"
          };
  }
}

export {
  fromNumber ,
}
/* No side effect */
