// Generated by ReScript, PLEASE EDIT WITH CARE


function make(street, city) {
  return {
          street: street,
          city: city
        };
}

var Street;

var ServedCity;

export {
  Street ,
  ServedCity ,
  make ,
}
/* No side effect */
