// Generated by ReScript, PLEASE EDIT WITH CARE


function between(origin, destination) {
  return {
          origin: origin,
          destination: destination
        };
}

var Address;

export {
  Address ,
  between ,
}
/* No side effect */
