// Generated by ReScript, PLEASE EDIT WITH CARE


function between(origin, destination) {
  return {
          origin: origin,
          destination: destination
        };
}

function origin(route) {
  return route.origin;
}

function destination(route) {
  return route.destination;
}

var Address;

export {
  Address ,
  between ,
  origin ,
  destination ,
}
/* No side effect */
