// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Shell_RideRequest from "./shell/Shell_RideRequest.res.js";

var origin = Shell_RideRequest.RequestAddress.make("56 rue de contrecoeur", "Montreal");

var destination = Shell_RideRequest.RequestAddress.make("Montréal-Pierre Elliott Trudeau International Airport", "Montreal");

var request = Shell_RideRequest.make(origin, destination);

await Shell_RideRequest.handle(request);

var RideRequest;

export {
  RideRequest ,
  origin ,
  destination ,
  request ,
}
/* origin Not a pure module */
