// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Core_ServedCity from "./core/Core_ServedCity.res.js";
import * as Shell_RideRequest from "./shell/Shell_RideRequest.res.js";

var city = Core_ServedCity.fromString("Montreal");

var montreal;

montreal = city.TAG === "Ok" ? await Shell_RideRequest.DB.add(city._0) : Js_exn.raiseError("Error happpend");

var origin = Shell_RideRequest.RequestAddress.make("0000 rue de contrecoeur", "Montreal");

var destination = Shell_RideRequest.RequestAddress.make("Montréal-Pierre Elliott Trudeau International Airport", "Montreal");

var request = Shell_RideRequest.make(origin, destination);

await Shell_RideRequest.handle(request);

var DB;

var ServedCity;

var RideRequest;

export {
  DB ,
  ServedCity ,
  RideRequest ,
  montreal ,
  origin ,
  destination ,
  request ,
}
/* city Not a pure module */
